version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100
    groups:
      expo:
        patterns:
          - "expo*"
          - "@expo/*"
      react:
        patterns:
          - "react*"
          - "@react*"
          - "@types/react"
      development:
        dependency-type: "development"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100
